spring:
  application:
    name: Smart Order
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=home-db;encrypt=false;
    username: sa
    password: Mysql@1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always    # shows db connection, disk space, etc.
    prometheus:
      access: UNRESTRICTED
  metrics:
    tags:
      application: smart-order
